# yaml-language-server: $schema=none
# Workflow for building and deploying the React Vite app to GitHub Pages
name: Deploy to GitHub Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build-and-deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      # yaml-language-server-disable
      - name: Checkout
        uses: actions/checkout@v4

      # yaml-language-server-disable
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: 'base/package-lock.json'

      - name: Install dependencies
        run: npm ci --prefix base

      - name: Build Vite application
        env:
          GITHUB_PAGES: 'true'
        run: |
          npm run build --prefix base
          cp base/dist/index.html base/dist/404.html

      # yaml-language-server-disable
      - name: Setup Pages
        uses: actions/configure-pages@v5

      # yaml-language-server-disable
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'base/dist'

      # yaml-language-server-disable
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
